USE [master]
GO

/****** Object:  Database [DevCampSQLProject]    Script Date: 6/26/2022 9:31:42 PM ******/
CREATE DATABASE [DevCampSQLProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DevCampSQLProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DevCampSQLProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DevCampSQLProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DevCampSQLProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DevCampSQLProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DevCampSQLProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DevCampSQLProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DevCampSQLProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DevCampSQLProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DevCampSQLProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET RECOVERY FULL 
GO

ALTER DATABASE [DevCampSQLProject] SET  MULTI_USER 
GO

ALTER DATABASE [DevCampSQLProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DevCampSQLProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DevCampSQLProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DevCampSQLProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DevCampSQLProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DevCampSQLProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DevCampSQLProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DevCampSQLProject] SET  READ_WRITE 
GO

